#配置数据源
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/credit?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: Dongsiqi@12
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # url: jdbc:mysql://10.0.29.91:3306/dw_tianyancha?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      # 配置多数据源时，如使用hikari连接池必须使用jdbc-url作为key，正常配置可以使用url
      jdbc-url: jdbc:mysql://localhost:3306/credit_ds?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: Dongsiqi@12

  cache:
    ehcache:
      config: classpath:/ehcache/ehcache-local.xml

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构 update
      ddl-auto: update

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

ratel:
  framework:
    #是否开启 swagger-ui
    swagger-enabled: true

  # 文件存储路径
  file:
#    path: /Users/dongchuang/Downloads/rtadmin/file/
    #avatar: /Users/dongchuang/Downloads/rtadmin/avatar/
    path: /data/nginx/jsth/app/file/
    avatar: /data/nginx/jsth/app/avatar/
    jarHtml: classpath:/html/  # none - 代表不实用jar包 中的静态文件
    html: /data/rate_app/file/html/
    #  jarHtml: none  #classpath:/html/  # none - 代表不实用jar包 中的静态文件
    #  html: D:\code\yn_yq\rtadmin-server\rtadmin-run\src\main\resources\html\
    # 文件大小 /M
    maxSize: 100
    avatarMaxSize: 5

  #jwt
  jwt:
    #表示 Token 颁发者的唯一标识
    issuer: http://192.168.3.174:8000
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # 必须使用最少88位的Base64对该令牌进行编码
    base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
    # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
    token-validity-in-seconds: 144000000000
    # 在线用户key
    online-key: online-token
    # 验证码
    code-key: code-key
    # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
    detect: 1800000
    # 续期时间范围，默认1小时，单位毫秒
    renew: 3600000

  #是否允许生成代码，生产环境设置为false
  generator:
      enabled: true

# 应用程序配置
application:
  file:
    storage:
      local: uploads
